
//登陆
export const USER_LOGIN = 'USER_LOGIN'

//登陆状态
export const LOGIN_STATUS = 'LOGIN_STATUS'
export const LOGIN_STATUS_GETTER = 'LOGIN_STATUS_GETTER'
export const LOGIN_STATUS_SETTER = 'LOGIN_STATUS_SETTER'


//首页banner
export const BANNER_LISTS = 'BANNER_LISTS'


//音乐播放相关

//播放列表集合
export const PLAY_MUSIC_LIST = 'PLAY_MUSIC_LIST'
export const PLAY_MUSIC_LIST_SETTER = 'PLAY_MUSIC_LIST_SETTER'
export const PLAY_MUSIC_LIST_GETTER = 'PLAY_MUSIC_LIST_GETTER'

//当前播放索引
export const PLAY_MUSIC_INDEX = 'PLAY_MUSIC_INDEX'
export const PLAY_MUSIC_INDEX_SETTER = 'PLAY_MUSIC_INDEX_SETTER'
export const PLAY_MUSIC_INDEX_GETTER = 'PLAY_MUSIC_INDEX_GETTER'

//播放列表id
export const PLAY_MUSIC_LIST_ID = 'PLAY_MUSIC_LIST_ID'
export const PLAY_MUSIC_LIST_ID_SETTER = 'PLAY_MUSIC_LIST_SETTER_ID'
export const PLAY_MUSIC_LIST_ID_GETTER = 'PLAY_MUSIC_LIST_GETTER_ID'

//音乐当前是否播放
export const MUSIC_IS_PLAY = 'MUSIC_IS_PLAY'
export const MUSIC_IS_PLAY_GETTER = 'MUSIC_IS_PLAY_GETTER'
export const MUSIC_IS_PLAY_SETTER = 'MUSIC_IS_PLAY_SETTER'

//音乐播放的类型
export const MUSIC_PLAY_TYPE = 'MUSIC_PLAY_TYPE'
export const MUSIC_PLAY_TYPE_GETTER = 'MUSIC_PLAY_TYPE_GETTER'
export const MUSIC_PLAY_TYPE_SETTER = 'MUSIC_PLAY_TYPE_SETTER'

//音乐播放内容
export const MUSIC_PLAY_CONTENT = 'MUSIC_PLAY_CONTENT'
export const MUSIC_PLAY_CONTENT_GETTER = 'MUSIC_PLAY_CONTENT_GETTER'
export const MUSIC_PLAY_CONTENT_SETTER = 'MUSIC_PLAY_CONTENT_SETTER'

//音乐播放时间
export const MUSIC_PLAY_TIME = 'MUSIC_PLAY_TIME'
export const MUSIC_PLAY_TIME_GETTER = 'MUSIC_PLAY_TIME_GETTER'
export const MUSIC_PLAY_TIME_SETTER = 'MUSIC_PLAY_TIME_SETTER'

//音乐总时长
export const MUSIC_DURATION_TIME = 'MUSIC_DURATION_TIME'
export const MUSIC_DURATION_TIME_GETTER = 'MUSIC_DURATION_TIME_GETTER'
export const MUSIC_DURATION_TIME_SETTER = 'MUSIC_DURATION_TIME_SETTER'

//音乐音量大小
export const MUSIC_VOL = 'MUSIC_VOL'
export const MUSIC_VOL_GETTER = 'MUSIC_VOL_GETTER'
export const MUSIC_VOL_SETTER = 'MUSIC_VOL_SETTER'

//正在播放音乐详情
export const MUSIC_PLAYING_DETAIL = 'MUSIC_PLAYING_DETAIL'
export const MUSIC_PLAYING_DETAIL_GETTER = 'MUSIC_PLAYING_DETAIL_GETTER'
export const MUSIC_PLAYING_DETAIL_SETTER = 'MUSIC_PLAYING_DETAIL_SETTER'

//正在播放音乐专辑近似色
export const MUSIC_PLAYING_COLOR = 'MUSIC_PLAYING_COLOR'
export const MUSIC_PLAYING_COLOR_GETTER = 'MUSIC_PLAYING_COLOR_GETTER'
export const MUSIC_PLAYING_COLOR_SETTER = 'MUSIC_PLAYING_COLOR_SETTER'

//音乐悬浮面板的显示与隐藏
export const MUSIC_SHOW_FIXED_MENU = 'MUSIC_SHOW_FIXED_MENU'
export const MUSIC_SHOW_FIXED_MENU_GETTER = 'MUSIC_SHOW_FIXED_MENU_GETTER'
export const MUSIC_SHOW_FIXED_MENU_SETTER = 'MUSIC_SHOW_FIXED_MENU_SETTER'
